name: PackPlugin
on:
  workflow_dispatch:
  push:
    branches:
      - v1

jobs:
  build:
    uses: FriendsOfShopware/actions/.github/workflows/store-shopware-cli.yml@main
    with:
      extensionName: FroshLazySizes
    secrets:
      accountUser: ${{ secrets.ACCOUNT_USER }}
      accountPassword: ${{ secrets.ACCOUNT_PASSWORD }}
      ghToken: ${{ secrets.GITHUB_TOKEN }}
