name: PackPlugin
on:
  push:
    branches:
      - v1

jobs:
  build:
    uses: FriendsOfShopware/actions/.github/workflows/store.yml@main
    with:
      extensionName: FroshLazySizes
      shopwareVersion: '6.4.10'
    secrets:
      accountUser: ${{ secrets.ACCOUNT_USER }}
      accountPassword: ${{ secrets.ACCOUNT_PASSWORD }}
      ghToken: ${{ secrets.GITHUB_TOKEN }}
